#pragma once
#define QEDEMON_APP_NAME "VkTest"
#define QEDEMON_APP_VERSION 1
#define QEDEMON_ENGINE_NAME "Qedemon"
#define QEDEMON_ENGINE_VERSION 1
#define QEDEMON_API_VERSION_MAYJOR 1
#define QEDEMON_API_VERSION_MINOR 0